@interface THAccessibility
- (BOOL)supportsCharts;
- (BOOL)supportsTableEditing;
- (id)canvasViewDescription;
- (void)addExtraSafeCategoryNamesToCollection:(id)a3;
- (void)addSafeCategoryNamesToCollection:(id)a3;
- (void)performExtraValidation;
- (void)performValidation;
@end

@implementation THAccessibility

- (void)performValidation
{
  v1102.receiver = self;
  v1102.super_class = (Class)THAccessibility;
  [(TSAccessibility *)&v1102 performValidation];
  __TSAccessibilityValidateInstanceMethodComplete(@"TSDCanvas", @"invalidateLayers", "v", v2, v3, v4, v5, v6, 0);
  __TSAccessibilityValidateProtocolMethod(@"TSDContainerRep", @"childReps", 1, 1);
  __TSAccessibilityValidateInstanceMethodComplete(@"TSDDrawableInfo", @"accessibilityDescriptions", "@", v7, v8, v9, v10, v11, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"TSDInteractiveCanvasController", @"canvasView", "@", v12, v13, v14, v15, v16, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"TSDInteractiveCanvasController", @"documentRoot", "@", v17, v18, v19, v20, v21, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"TSDRep", @"isDraggable", "B", v22, v23, v24, v25, v26, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"TSKScrollView", @"delegate", "@", v27, v28, v29, v30, v31, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"TSPObject", @"context", "@", v32, v33, v34, v35, v36, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THTSWPInteractiveCanvasController", @"didBeginEditingText", "v", v37, v38, v39, v40, v41, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THImageInfo", @"popUpInfo", "@", v42, v43, v44, v45, v46, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THImageRep", @"pressableAction", "i", v47, v48, v49, v50, v51, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THImageRep", @"handleNavigateNextCommand", "v", v52, v53, v54, v55, v56, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THImageRep", @"handleNavigatePreviousCommand", "v", v57, v58, v59, v60, v61, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THInteractiveCanvasController", @"delegate", "@", v62, v63, v64, v65, v66, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THInteractiveCanvasController", @"documentNavigator", "@", v67, v68, v69, v70, v71, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THInteractiveCanvasController", @"handleHyperlink:hitRep:", "v", v72, v73, v74, v75, v76, "@");
  __TSAccessibilityValidateInstanceMethodComplete(@"THInteractiveCanvasController", @"linkForHyperlinkField:", "@", v77, v78, v79, v80, v81, "@");
  __TSAccessibilityValidateInstanceMethodComplete(@"THModelContentNode", @"relativePageIndexForInfo:forPresentationType:", "Q", v82, v83, v84, v85, v86, "@");
  __TSAccessibilityValidateInstanceMethodComplete(@"THModelContentNode", @"bodyStorageForPresentationType:", "@", v87, v88, v89, v90, v91, "@");
  __TSAccessibilityValidateInstanceMethodComplete(@"THModelContentNode", @"infoForNodeUniqueID:forPresentationType:", "@", v92, v93, v94, v95, v96, "@");
  __TSAccessibilityValidateInstanceMethodComplete(@"THModelContentNode", @"nodeUniqueIDForInfo:", "@", v97, v98, v99, v100, v101, "@");
  __TSAccessibilityValidateInstanceMethodComplete(@"THPageRep", @"marginNotesController", "@", v102, v103, v104, v105, v106, 0);
  __TSAccessibilityValidateClassMethodComplete(@"TSDContainerRep", @"containerRep:hitRep:withGesture:passingTest:", "@", v107, v108, v109, v110, v111, "@");
  __TSAccessibilityValidateInstanceMethodComplete(@"THAnnotationNoteCardInfo", @"annotation", "@", v112, v113, v114, v115, v116, 0);
  __TSAccessibilityValidateIvarType(@"THCachedAnnotation", "_annotationNote", "NSString");
  __TSAccessibilityValidateIvarType(@"THCachedAnnotation", "_annotationRepresentativeText", "NSString");
  __TSAccessibilityValidateIvarType(@"THCachedAnnotation", "_annotationStyle", "i");
  __TSAccessibilityValidateInstanceMethodComplete(@"THCachedAnnotation", @"annotationStorageRange", "{_NSRange=QQ}", v117, v118, v119, v120, v121, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THCachedAnnotation", @"pageNumberString", "{NSString=#}", v122, v123, v124, v125, v126, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THCachedAnnotation", @"title", "{NSString=#}", v127, v128, v129, v130, v131, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentNavigationModel", @"absolutePageIndexForContentNodeRelativePageIndex:inContentNode:forPresentationType:", "Q", v132, v133, v134, v135, v136, "Q");
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentNavigationModel", @"chapterAndNumberStringForNavigationUnit:", "@", v137, v138, v139, v140, v141, "@");
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentNavigationModel", @"contentNodeForAbsolutePageIndex:", "@", v142, v143, v144, v145, v146, "Q");
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentNavigationModel", @"majorSnippetForAbsolutePageIndex:withDocumentRoot:forPresentationType:", "@", v147, v148, v149, v150, v151, "Q");
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentNavigationModel", @"minorSnippetForAbsolutePageIndex:withDocumentRoot:forPresentationType:", "@", v152, v153, v154, v155, v156, "Q");
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentNavigationModel", @"navigationUnitContainingContentNode:", "@", v157, v158, v159, v160, v161, "@");
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentNavigationModel", @"p_chapterNodeForContentNode:", "@", v162, v163, v164, v165, v166, "@");
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentNavigationModel", @"p_lessonNodeForContentNode:", "@", v167, v168, v169, v170, v171, "@");
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentNavigationModel", @"pageNumberStringForAbsolutePageIndex:forPresentationType:", "@", v172, v173, v174, v175, v176, "q");
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentNavigator", @"absolutePageIndexForBeginningOfSection", "Q", v177, v178, v179, v180, v181, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentNavigator", @"absolutePageIndexForEndOfSection", "Q", v182, v183, v184, v185, v186, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentNavigator", @"currentAbsolutePageIndex", "Q", v187, v188, v189, v190, v191, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentNavigator", @"currentContentNode", "@", v192, v193, v194, v195, v196, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentNavigator", @"documentRoot", "@", v197, v198, v199, v200, v201, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentNavigator", @"interactiveCanvasController", "@", v202, v203, v204, v205, v206, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentNavigator", @"lastAbsolutePageIndex", "Q", v207, v208, v209, v210, v211, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentNavigator", @"lastAbsolutePageIndex", "Q", v212, v213, v214, v215, v216, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentNavigator", @"p_jumpToStorageAnchor:pulse:", "v", v217, v218, v219, v220, v221, "@");
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentNavigator", @"sectionController", "@", v222, v223, v224, v225, v226, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentNavigator", @"setVisibleAbsolutePhysicalPageIndex:animated:", "v", v227, v228, v229, v230, v231, "Q");
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentRoot", @"context", "@", v232, v233, v234, v235, v236, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentRoot", @"isEPUB", "B", v237, v238, v239, v240, v241, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentRoot", @"navigationModel", "@", v242, v243, v244, v245, v246, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentRoot", @"rootNode", "@", v247, v248, v249, v250, v251, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentRoot", @"tocModel", "@", v252, v253, v254, v255, v256, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THGlossaryNoteCardInfo", @"glossaryEntry", "@", v257, v258, v259, v260, v261, 0);
  __TSAccessibilityValidateIsKindOfClass(@"THModelContainerNode", @"THModelNode");
  __TSAccessibilityValidateInstanceMethodComplete(@"THModelContainerNode", @"indexOfNode:", "Q", v262, v263, v264, v265, v266, "@");
  __TSAccessibilityValidateIsKindOfClass(@"THModelContentNode", @"THModelNode");
  __TSAccessibilityValidateInstanceMethodComplete(@"THModelGlossaryEntry", @"summaryText", "@", v267, v268, v269, v270, v271, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THModelGlossaryEntry", @"term", "@", v272, v273, v274, v275, v276, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THModelLink", @"initWithTarget:context:", "@", v277, v278, v279, v280, v281, "@");
  __TSAccessibilityValidateIsKindOfClass(@"THModelNode", @"TSPObject");
  __TSAccessibilityValidateInstanceMethodComplete(@"THModelNode", @"absolutePageRangeForPresentationType:", "{_NSRange=QQ}", v282, v283, v284, v285, v286, "@");
  __TSAccessibilityValidateInstanceMethodComplete(@"THModelNode", @"contentNodeForRelativePageIndex:forPresentationType:", "@", v287, v288, v289, v290, v291, "Q");
  __TSAccessibilityValidateInstanceMethodComplete(@"THModelNode", @"parent", "@", v292, v293, v294, v295, v296, 0);
  __TSAccessibilityValidateIvarType(@"THNoteCardContentLayer", "_cardNumberLabel", "THMultiLineLabel");
  __TSAccessibilityValidateIvarType(@"THNoteCardLayer", "_delegate", "<THNoteCardLayerDelegate>");
  __TSAccessibilityValidateInstanceMethodComplete(@"THNoteCardLayer", @"frontLayer", "@", v297, v298, v299, v300, v301, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THNoteCardLayer", @"isBottomCard", "B", v302, v303, v304, v305, v306, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THNoteCardLayer", @"isFlipped", "B", v307, v308, v309, v310, v311, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THNoteCardLayer", @"isTopCard", "B", v312, v313, v314, v315, v316, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THNoteCardLayer", @"_frontLayer", "@", v317, v318, v319, v320, v321, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THNoteCardContentLayer", @"_bodyLayer", "@", v322, v323, v324, v325, v326, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THNoteCardEmptyLayer", @"_headingLabel", "@", v327, v328, v329, v330, v331, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THNoteCardEmptyLayer", @"_bodyLabel", "@", v332, v333, v334, v335, v336, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THNoteCardsController", @"animateBottomCardToTopInDirection:", "v", v337, v338, v339, v340, v341, "{CGPoint=dd}");
  __TSAccessibilityValidateInstanceMethodComplete(@"THNoteCardsController", @"animateTopCardToBottomInDirection:", "v", v342, v343, v344, v345, v346, "{CGPoint=dd}");
  __TSAccessibilityValidateInstanceMethodComplete(@"THNoteCardsController", @"isShowingEmptyStudyCard", "B", v347, v348, v349, v350, v351, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THNoteCardsController", @"p_handleDelayedCardUpdate", "v", v352, v353, v354, v355, v356, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THNoteCardsController", @"p_noteCardsForInfos:", "@", v357, v358, v359, v360, v361, "@");
  __TSAccessibilityValidateInstanceMethodComplete(@"THNoteCardsController", @"p_topNoteCard", "@", v362, v363, v364, v365, v366, 0);
  __TSAccessibilityValidateClassMethodComplete(@"THPresentationType", @"paginatedPresentationTypeInContext:", "@", v367, v368, v369, v370, v371, "@");
  __TSAccessibilityValidateInstanceMethodComplete(@"THTOCModel", @"tiles", "@", v372, v373, v374, v375, v376, 0);
  __TSAccessibilityValidateIsKindOfClass(@"THTOCTileModel", @"THTOCModel");
  __TSAccessibilityValidateInstanceMethodComplete(@"THTOCTileModel", @"landscapeEntries", "@", v377, v378, v379, v380, v381, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THTOCTileModelEntry", @"displayPageNumber", "@", v382, v383, v384, v385, v386, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THTOCTileModelEntry", @"sectionIdentifier", "@", v387, v388, v389, v390, v391, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THTOCTileModelEntry", @"title", "@", v392, v393, v394, v395, v396, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWPHighlightController", @"annotationForRange:", "@", v397, v398, v399, v400, v401, "{_NSRange=QQ}");
  __TSAccessibilityValidateInstanceMethodComplete(@"THWPHighlightController", @"annotationsForRange:", "@", v402, v403, v404, v405, v406, "{_NSRange=QQ}");
  __TSAccessibilityValidateIsKindOfClass(@"THWPTOCRep", @"THWPRep");
  __TSAccessibilityValidateIsKindOfClass(@"THWPTOCStorage", @"THWPStorage");
  __TSAccessibilityValidateInstanceMethodComplete(@"THWAdornmentController", @"setAdornmentsVisible:", "v", v407, v408, v409, v410, v411, "B");
  __TSAccessibilityValidateInstanceMethodComplete(@"THWAdornmentController", @"setAdornmentsVisible:buttonVisible:controlsVisible:forceVisibility:animated:completionBlock:", "v", v412, v413, v414, v415, v416, "B");
  __TSAccessibilityValidateInstanceMethodComplete(@"THWAdornmentController", @"bottomPanel", "@", v417, v418, v419, v420, v421, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWAdornmentController", @"bottomPanel", "@", v422, v423, v424, v425, v426, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWAdornmentController", @"closeButton", "@", v427, v428, v429, v430, v431, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWAdornmentController", @"controlPanel", "@", v432, v433, v434, v435, v436, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWAdornmentController", @"expandedRep", "@", v437, v438, v439, v440, v441, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWAdornmentController", @"p_updateAdornmentVisibilityAnimated:forced:completionBlock:", "v", v442, v443, v444, v445, v446, "B");
  __TSAccessibilityValidateInstanceMethodComplete(@"THWAdornmentController", @"topPanel", "@", v447, v448, v449, v450, v451, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWAdornmentPanel", @"autosizedCanvasController", "@", v452, v453, v454, v455, v456, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWAdornmentPanel", @"view", "@", v457, v458, v459, v460, v461, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWAudioRep", @"childReps", "@", v462, v463, v464, v465, v466, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWAudioRep", @"isPaused", "B", v467, v468, v469, v470, v471, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWAudioRep", @"isPlaying", "B", v472, v473, v474, v475, v476, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWAudioRep", @"movieInfo", "@", v477, v478, v479, v480, v481, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWAudioRep", @"pause", "v", v482, v483, v484, v485, v486, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWAudioRep", @"play", "v", v487, v488, v489, v490, v491, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWAutosizedCanvasController", @"canvasView", "@", v492, v493, v494, v495, v496, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWButtonControlLayout", @"index", "Q", v497, v498, v499, v500, v501, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWButtonControlLayout", @"tag", "Q", v502, v503, v504, v505, v506, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWButtonControlLayout", @"index", "Q", v507, v508, v509, v510, v511, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWButtonControlRep", @"delegate", "@", v512, v513, v514, v515, v516, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWButtonControlRep", @"layout", "@", v517, v518, v519, v520, v521, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWButtonControlRep", @"p_interactionEnabled", "B", v522, v523, v524, v525, v526, 0);
  __TSAccessibilityValidateProtocolMethod(@"THWButtonControlDelegate", @"buttonControlWasPressed:", 1, 1);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWAVAudioUI", @"hiddenPlayButton", "@", v527, v528, v529, v530, v531, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWAVTransportController", @"movieIsPlaying", "B", v532, v533, v534, v535, v536, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWAVTransportController", @"play", "v", v537, v538, v539, v540, v541, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWAVTransportController", @"playButtonRep", "@", v542, v543, v544, v545, v546, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWAVTransportController", @"transportUI", "@", v547, v548, v549, v550, v551, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWAVTransportLayout", @"transportController", "@", v552, v553, v554, v555, v556, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWAVTransportRep", @"layout", "@", v557, v558, v559, v560, v561, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWAVTransportUI", @"onCanvasViews", "@", v562, v563, v564, v565, v566, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWAVTransportUI", @"pause", "v", v567, v568, v569, v570, v571, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWAVTransportUI", @"play", "v", v572, v573, v574, v575, v576, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWAVTransportUI", @"playButton", "@", v577, v578, v579, v580, v581, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWAVTransportUI", @"scrubber", "@", v582, v583, v584, v585, v586, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWAVTransportUI", @"transportController", "@", v587, v588, v589, v590, v591, 0);
  __TSAccessibilityValidateIsKindOfClass(@"THWDrawablesWidgetInfo", @"TSDDrawableInfo");
  __TSAccessibilityValidateInstanceMethodComplete(@"THWDrawablesWidgetInfo", @"expandedStageDrawable", "@", v592, v593, v594, v595, v596, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWDrawablesWidgetInfo", @"stageDrawable", "@", v597, v598, v599, v600, v601, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWGalleryInfo", @"items", "@", v602, v603, v604, v605, v606, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWGalleryInfo", @"titleString", "@", v607, v608, v609, v610, v611, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWGalleryItem", @"captionStorage", "@", v612, v613, v614, v615, v616, 0);
  __TSAccessibilityValidateIsKindOfClass(@"THWGalleryRep", @"TSDRep");
  __TSAccessibilityValidateInstanceMethodComplete(@"THWGalleryRep", @"addChildViewsToArray:", "v", v617, v618, v619, v620, v621, "@");
  __TSAccessibilityValidateInstanceMethodComplete(@"THWGalleryRep", @"currentItem", "@", v622, v623, v624, v625, v626, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWGalleryRep", @"p_goToPage:", "v", v627, v628, v629, v630, v631, "Q");
  __TSAccessibilityValidateInstanceMethodComplete(@"THWGalleryRep", @"p_itemAtIndex:", "@", v632, v633, v634, v635, v636, "Q");
  __TSAccessibilityValidateIvarType(@"THWGalleryRep", "_stageCanvasController", "THWPagedCanvasController");
  __TSAccessibilityValidateInstanceMethodComplete(@"THWGalleryRep", @"stageCanvasController", "@", v637, v638, v639, v640, v641, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWGalleryRep", @"thumbnailTrackCanvasController", "@", v642, v643, v644, v645, v646, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWGutterInfo", @"expandedDrawableToPresent", "@", v647, v648, v649, v650, v651, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWGutterInfo", @"titleShape", "@", v652, v653, v654, v655, v656, 0);
  __TSAccessibilityValidateIsKindOfClass(@"THWGutterRep", @"TSDContainerRep");
  __TSAccessibilityValidateInstanceMethodComplete(@"THWInteractiveImageCalloutInfo", @"descriptionStorage", "@", v657, v658, v659, v660, v661, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWInteractiveImageCalloutInfo", @"titleStorage", "@", v662, v663, v664, v665, v666, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWInteractiveImageCalloutLayout", @"calloutInfo", "@", v667, v668, v669, v670, v671, 0);
  __TSAccessibilityValidateIsKindOfClass(@"THWInteractiveImageCalloutRep", @"TSDContainerRep");
  __TSAccessibilityValidateInstanceMethodComplete(@"THWInteractiveImageCalloutRep", @"p_animatingCallouts", "B", v672, v673, v674, v675, v676, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWInteractiveImageCalloutRep", @"p_host", "@", v677, v678, v679, v680, v681, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWInteractiveImageCalloutRep", @"updateFromLayout", "v", v682, v683, v684, v685, v686, 0);
  __TSAccessibilityValidateIsKindOfClass(@"THWInteractiveImageRadioPanelRep", @"THWControlContainerRep");
  __TSAccessibilityValidateIvarType(@"THWInteractiveImageRadioPanelRep", "_nextButtonRep", "THWButtonControlRep");
  __TSAccessibilityValidateIvarType(@"THWInteractiveImageRadioPanelRep", "_previousButtonRep", "THWButtonControlRep");
  __TSAccessibilityValidateIsKindOfClass(@"THWInteractiveImageWidgetRep", @"TSDContainerRep");
  __TSAccessibilityValidateInstanceMethodComplete(@"THWInteractiveImageWidgetRep", @"calloutInfoForDisplay", "@", v687, v688, v689, v690, v691, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWInteractiveImageWidgetRep", @"interactiveImageCalloutPressed:", "v", v692, v693, v694, v695, v696, "@");
  __TSAccessibilityValidateInstanceMethodComplete(@"THWInteractiveImageWidgetRep", @"overlayableZoomableCanvasController:didEndZoomingAtScale:", "v", v697, v698, v699, v700, v701, "@");
  __TSAccessibilityValidateInstanceMethodComplete(@"THWInteractiveImageWidgetRep", @"overlayableZoomableCanvasController:expandBoundsForHitTesting:", "{CGRect={CGPoint=dd}{CGSize=dd}}", v702, v703, v704, v705, v706, "@");
  __TSAccessibilityValidateInstanceMethodComplete(@"THWInteractiveImageWidgetRep", @"p_widgetInteractionDisabledOnPage", "B", v707, v708, v709, v710, v711, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWInteractiveImageWidgetRep", @"stageCanvasController", "@", v712, v713, v714, v715, v716, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWKeynoteShowRep", @"kpfPlayer", "@", v717, v718, v719, v720, v721, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWMovieInfo", @"mediaDisplayName", "@", v722, v723, v724, v725, v726, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWOverlayableZoomableCanvasController", @"delegate", "@", v727, v728, v729, v730, v731, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWOverlayableZoomableCanvasController", @"interactiveCanvasController:expandBoundsForHitTesting:", "{CGRect={CGPoint=dd}{CGSize=dd}}", v732, v733, v734, v735, v736, "@");
  __TSAccessibilityValidateInstanceMethodComplete(@"THWOverlayableZoomableCanvasController", @"scrollContainerICC", "@", v737, v738, v739, v740, v741, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWOverlayableZoomableCanvasController", @"scrollContentICC", "@", v742, v743, v744, v745, v746, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWPageControlLayout", @"currentPage", "Q", v747, v748, v749, v750, v751, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWPageControlLayout", @"numberOfPages", "Q", v752, v753, v754, v755, v756, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWPageControlRep", @"p_changeToPageAtIndex:", "v", v757, v758, v759, v760, v761, "Q");
  __TSAccessibilityValidateInstanceMethodComplete(@"THWPagedCanvasController", @"createViewIfNeededWithFrame:viewScale:", "B", v762, v763, v764, v765, v766, "{CGRect={CGPoint=dd}{CGSize=dd}}");
  __TSAccessibilityValidateInstanceMethodComplete(@"THWPagedCanvasController", @"delegate", "@", v767, v768, v769, v770, v771, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWPagedCanvasController", @"interactiveCanvasController", "@", v772, v773, v774, v775, v776, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWPagedCanvasController", @"scrollView", "@", v777, v778, v779, v780, v781, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWPagedCanvasController", @"teardownView", "v", v782, v783, v784, v785, v786, 0);
  __TSAccessibilityValidateIsKindOfClass(@"THWPagedCanvasControlRep", @"TSDRep");
  __TSAccessibilityValidateInstanceMethodComplete(@"THWPagedCanvasControlRep", @"pagedCanvasController", "@", v787, v788, v789, v790, v791, 0);
  __TSAccessibilityValidateIsKindOfClass(@"THWPEditingController", @"TSWPEditingController");
  __TSAccessibilityValidateInstanceMethodComplete(@"THWPEditingController", @"canEditTextString", "B", v792, v793, v794, v795, v796, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWPEditingController", @"canPerformEditorAction:withSender:", "i", v797, v798, v799, v800, v801, ":");
  __TSAccessibilityValidateInstanceMethodComplete(@"THWPopUpContentProvider", @"initWithPopUpInfo:scale:documentRoot:scrollableCanvasHost:bookNavigator:documentNavigator:", "@", v802, v803, v804, v805, v806, "@");
  __TSAccessibilityValidateInstanceMethodComplete(@"THWPopUpContentProvider", @"popoverContentView", "@", v807, v808, v809, v810, v811, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWReviewControlsRep", @"checkAnswerButtonState", "i", v812, v813, v814, v815, v816, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWReviewControlsRep", @"childReps", "@", v817, v818, v819, v820, v821, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWReviewControlsRep", @"prevButtonHidden", "B", v822, v823, v824, v825, v826, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWReviewControlsRep", @"nextButtonHidden", "B", v827, v828, v829, v830, v831, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWReviewDraggablePlacardLayout", @"contentImageAccessibilityDescription", "@", v832, v833, v834, v835, v836, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWReviewDraggablePlacardLayout", @"index", "Q", v837, v838, v839, v840, v841, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWReviewDraggablePlacardRep", @"contentTextRep", "@", v842, v843, v844, v845, v846, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWReviewImageAnswerChoiceState", @"choiceAccessibilityDescription", "@", v847, v848, v849, v850, v851, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWReviewImageAnswerChoiceState", @"choiceState", "i", v852, v853, v854, v855, v856, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWReviewLayout", @"questionCount", "Q", v857, v858, v859, v860, v861, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWReviewLayout", @"questionIndex", "Q", v862, v863, v864, v865, v866, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWReviewRep", @"control:repWasAdded:", "v", v867, v868, v869, v870, v871, "@");
  __TSAccessibilityValidateInstanceMethodComplete(@"THWReviewRep", @"control:repWillBeRemoved:", "v", v872, v873, v874, v875, v876, "@");
  __TSAccessibilityValidateInstanceMethodComplete(@"THWReviewRep", @"isExpanded", "B", v877, v878, v879, v880, v881, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWReviewRep", @"p_checkQuestionAnswer:", "v", v882, v883, v884, v885, v886, "@");
  __TSAccessibilityValidateInstanceMethodComplete(@"THWReviewRep", @"p_repForQuestion:", "@", v887, v888, v889, v890, v891, "@");
  __TSAccessibilityValidateInstanceMethodComplete(@"THWReviewSummaryLayout", @"delegate", "@", v892, v893, v894, v895, v896, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWReviewSummaryLayout", @"checkingLayout", "@", v897, v898, v899, v900, v901, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWReviewSummaryLayout", @"resultsLayout", "@", v902, v903, v904, v905, v906, 0);
  __TSAccessibilityValidateIsKindOfClass(@"THWReviewSummaryRep", @"TSDContainerRep");
  __TSAccessibilityValidateInstanceMethodComplete(@"THWReviewSummaryRep", @"canvas", "@", v907, v908, v909, v910, v911, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWReviewSummaryRep", @"didUpdateLayer:", "v", v912, v913, v914, v915, v916, "@");
  __TSAccessibilityValidateInstanceMethodComplete(@"THWReviewSummaryRep", @"layout", "@", v917, v918, v919, v920, v921, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWReviewTextAnswerLayout", @"index", "Q", v922, v923, v924, v925, v926, 0);
  __TSAccessibilityValidateIsKindOfClass(@"THWReviewTextAnswerRep", @"TSDContainerRep");
  __TSAccessibilityValidateInstanceMethodComplete(@"THWReviewTextAnswerRep", @"p_answerAccessibilityDescription", "@", v927, v928, v929, v930, v931, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWReviewTextAnswerRep", @"p_answerText", "@", v932, v933, v934, v935, v936, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWReviewTextAnswerRep", @"p_selectAnswer", "v", v937, v938, v939, v940, v941, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWReviewTextAnswerRep", @"updateRadioState", "v", v942, v943, v944, v945, v946, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWReviewTextAnswerRep", @"setRadioState:", "v", v947, v948, v949, v950, v951, "i");
  __TSAccessibilityValidateProtocolMethod(@"THWReviewSummaryLayoutDelegate", @"reviewSummaryShouldShowResults", 1, 1);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWScrollableCanvasController", @"delegate", "@", v952, v953, v954, v955, v956, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWScrollableCanvasController", @"interactiveCanvasController", "@", v957, v958, v959, v960, v961, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWScrollableCanvasController", @"scrollView", "@", v962, v963, v964, v965, v966, 0);
  __TSAccessibilityValidateIsKindOfClass(@"THWScrollableCanvasControlRep", @"TSDRep");
  __TSAccessibilityValidateInstanceMethodComplete(@"THWScrollableCanvasControlRep", @"scrollableCanvasController", "@", v967, v968, v969, v970, v971, 0);
  __TSAccessibilityValidateIvarType(@"THWLabelControlRep", "_labelLayer", "THWLabelLayer");
  __TSAccessibilityValidateInstanceMethodComplete(@"THWLabelLayer", @"string", "@", v972, v973, v974, v975, v976, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWViewportRep", @"scrollableCanvasController", "@", v977, v978, v979, v980, v981, 0);
  __TSAccessibilityValidateIsKindOfClass(@"TSKDocumentRoot", @"TSPObject");
  __TSAccessibilityValidateInstanceMethodComplete(@"THWZoomableCanvasController", @"delegate", "@", v982, v983, v984, v985, v986, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"TSWPopoverController", @"contentProvider", "@", v987, v988, v989, v990, v991, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"TSWPopoverController", @"dismissPopoverAnimated:", "v", v992, v993, v994, v995, v996, "B");
  __TSAccessibilityValidateInstanceMethodComplete(@"TSWPopoverController", @"isPopoverVisible", "B", v997, v998, v999, v1000, v1001, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"CAKPFPlayerController", @"gotoPreviousEvent", "v", v1002, v1003, v1004, v1005, v1006, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"CAKPFPlayerController", @"gotoPreviousSlide", "v", v1007, v1008, v1009, v1010, v1011, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"CAKPFPlayerController", @"handleTouchAtLocation:", "B", v1012, v1013, v1014, v1015, v1016, "{CGPoint=dd}");
  __TSAccessibilityValidateInstanceMethodComplete(@"CAKPFPlayerController", @"hyperlinksRectArray", "@", v1017, v1018, v1019, v1020, v1021, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"CAKPFPlayerController", @"prepareWithEndShowHandler:", "v", v1022, v1023, v1024, v1025, v1026, "@?");
  __TSAccessibilityValidateInstanceMethodComplete(@"CAKPFPlayerController", @"p_gotoEventIndex:skipBreadCrumb:shouldAutoPlay:", "v", v1027, v1028, v1029, v1030, v1031, "Q");
  __TSAccessibilityValidateInstanceMethodComplete(@"CAKPFPlayerController", @"p_triggerNextEvent", "v", v1032, v1033, v1034, v1035, v1036, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"CAKPFPlayerController", @"transportControlCloneCanGotoNext", "B", v1037, v1038, v1039, v1040, v1041, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"CAKPFSession", @"currentEvent", "@", v1042, v1043, v1044, v1045, v1046, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"CAKPFSession", @"KPFDocument", "@", v1047, v1048, v1049, v1050, v1051, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"CAKPFSession", @"nextEvent", "@", v1052, v1053, v1054, v1055, v1056, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"CAKPFSession", @"playbackStatus", "i", v1057, v1058, v1059, v1060, v1061, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"KPFDocument", @"eventIndexForSlideIndex:", "Q", v1062, v1063, v1064, v1065, v1066, "Q");
  __TSAccessibilityValidateInstanceMethodComplete(@"KPFEvent", @"hyperlinkAtLocation:", "@", v1067, v1068, v1069, v1070, v1071, "{CGPoint=dd}");
  __TSAccessibilityValidateInstanceMethodComplete(@"KPFEvent", @"isAutomatic", "B", v1072, v1073, v1074, v1075, v1076, 0);
  __TSAccessibilityValidateIvarType(@"CAKPFPlayerController", "mSession", "CAKPFSession");
  __TSAccessibilityValidateInstanceMethodComplete(@"THWSceneController", @"sceneView", "@", v1077, v1078, v1079, v1080, v1081, 0);
  __TSAccessibilityValidateIsKindOfClass(@"THWSceneRep", @"TSDRep");
  __TSAccessibilityValidateInstanceMethodComplete(@"THWSceneRep", @"expandedRepController", "@", v1082, v1083, v1084, v1085, v1086, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWSceneRep", @"isExpanded", "B", v1087, v1088, v1089, v1090, v1091, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWSceneRep", @"p_setupSceneControllerIfNecessary:", "v", v1092, v1093, v1094, v1095, v1096, "B");
  __TSAccessibilityValidateInstanceMethodComplete(@"THWSceneRep", @"replaceContentsFromRep:", "v", v1097, v1098, v1099, v1100, v1101, "@");
}

- (void)addSafeCategoryNamesToCollection:(id)a3
{
  v4.receiver = self;
  v4.super_class = (Class)THAccessibility;
  -[TSAccessibility addSafeCategoryNamesToCollection:](&v4, "addSafeCategoryNamesToCollection:");
  [a3 addObject:@"THTSDCanvasAccessibility"];
  [a3 addObject:@"THTSDCanvasViewAccessibility"];
  [a3 addObject:@"THTSDContainerRepAccessibility"];
  [a3 addObject:@"THTSDDrawableInfoAccessibility"];
  [a3 addObject:@"THTSDImageRepAccessibility"];
  [a3 addObject:@"THTSDInteractiveCanvasControllerAccessibility"];
  [a3 addObject:@"THTSDLayoutAccessibility"];
  [a3 addObject:@"THTSDRepAccessibility"];
  [a3 addObject:@"THTSDShapeRepAccessibility"];
  [a3 addObject:@"THTSWPRepAccessibility"];
  [a3 addObject:@"THTSWPInteractiveCanvasControllerAccessibility"];
  [a3 addObject:@"THTSWPShapeRepAccessibility"];
  [a3 addObject:@"TSKScrollViewAccessibility"];
  [a3 addObject:@"THCachedAnnotationAccessibility"];
  [a3 addObject:@"THContainerRepAccessibility"];
  [a3 addObject:@"THDisplaySettingsViewControllerAccessibility"];
  [a3 addObject:@"THDocumentNavigationModelAccessibility"];
  [a3 addObject:@"THDocumentNavigatorAccessibility"];
  [a3 addObject:@"THDocumentRootAccessibility"];
  [a3 addObject:@"THInteractiveCanvasControllerAccessibility"];
  [a3 addObject:@"THModelContainerNodeAccessibility"];
  [a3 addObject:@"THModelContentNodeAccessibility"];
  [a3 addObject:@"THModelLinkAccessibility"];
  [a3 addObject:@"THModelNodeAccessibility"];
  [a3 addObject:@"THPageRepAccessibility"];
  [a3 addObject:@"THPresentationTypeAccessibility"];
  [a3 addObject:@"THScrollViewWithPassthroughAccessibility"];
  [a3 addObject:@"THSectionControllerAccessibility"];
  [a3 addObject:@"THTOCModelAccessibility"];
  [a3 addObject:@"THTOCTileModelAccessibility"];
  [a3 addObject:@"THTOCTileModelEntryAccessibility"];
  [a3 addObject:@"THWAdornmentControllerAccessibility"];
  [a3 addObject:@"THWAdornmentPanelAccessibility"];
  [a3 addObject:@"THWPEditingControllerAccessibility"];
  [a3 addObject:@"THWPHighlightControllerAccessibility"];
  [a3 addObject:@"THWPopUpContentProviderAccessibility"];
  [a3 addObject:@"TSWPopoverControllerAccessibility"];
  [a3 addObject:@"THWAdornmentCloseButtonAccessibility"];
  [a3 addObject:@"THWDrawablesWidgetInfoAccessibility"];
  [a3 addObject:@"THWOverlayableZoomableCanvasControllerAccessibility"];
  [a3 addObject:@"THWPageControlRepAccessibility"];
  [a3 addObject:@"THWPagedCanvasControllerAccessibility"];
  [a3 addObject:@"THWPagedCanvasControlRepAccessibility"];
  [a3 addObject:@"THWPRepAccessibility"];
  [a3 addObject:@"THWScrollableCanvasControllerAccessibility"];
  [a3 addObject:@"THWScrollableCanvasControlRepAccessibility"];
  [a3 addObject:@"THWPTOCRepAccessibility"];
  [a3 addObject:@"THWViewportRepAccessibility"];
  [a3 addObject:@"THWWidgetBackgroundRepAccessibility"];
  [a3 addObject:@"THWZoomableCanvasControllerAccessibility"];
  [a3 addObject:@"THImageInfoAccessibility"];
  [a3 addObject:@"THImageRepAccessibility"];
  [a3 addObject:@"THWAudioRepAccessibility"];
  [a3 addObject:@"THWAVTransportControllerAccessibility"];
  [a3 addObject:@"THWAVTransportRepAccessibility"];
  [a3 addObject:@"THWAVTransportUIAccessibility"];
  [a3 addObject:@"THWButtonControlRepAccessibility"];
  [a3 addObject:@"THWMovieInfoAccessibility"];
  [a3 addObject:@"THWGalleryItemAccessibility"];
  [a3 addObject:@"THWGalleryRepAccessibility"];
  [a3 addObject:@"THGlossaryEntryViewControllerAccessibility"];
  [a3 addObject:@"THWReviewControlsRepAccessibility"];
  [a3 addObject:@"THWReviewDraggablePlacardRepAccessibility"];
  [a3 addObject:@"THWReviewImageAnswerChoiceStateAccessibility"];
  [a3 addObject:@"THWReviewInfoAccessibility"];
  [a3 addObject:@"THWReviewRepAccessibility"];
  [a3 addObject:@"THWReviewSummaryRepAccessibility"];
  [a3 addObject:@"THWReviewTextAnswerRepAccessibility"];
  [a3 addObject:@"THWInteractiveImageCalloutRepAccessibility"];
  [a3 addObject:@"THWInteractiveImageRadioPanelRepAccessibility"];
  [a3 addObject:@"THWInteractiveImageWidgetRepAccessibility"];
  [a3 addObject:@"THWSceneControllerAccessibility"];
  [a3 addObject:@"THWSceneRepAccessibility"];
  [a3 addObject:@"THWSceneViewAccessibility"];
  [a3 addObject:@"CAKPFPlayerControllerAccessibility"];
  [a3 addObject:@"THWKeynoteRepAccessibility"];
  [a3 addObject:@"THWKeynoteShowRepAccessibility"];
  [a3 addObject:@"THWTransportControlRepAccessibility"];
  [a3 addObject:@"THAnnotationNoteCardInfoAccessibility"];
  [a3 addObject:@"THEmptyNoteCardInfoAccessibility"];
  [a3 addObject:@"THGlossaryNoteCardInfoAccessibility"];
  [a3 addObject:@"THModelGlossaryEntryAccessibility"];
  [a3 addObject:@"THNoteCardContentLayerAccessibility"];
  [a3 addObject:@"THNoteCardLayerAccessibility"];
  [a3 addObject:@"THNoteCardsControllerAccessibility"];
  [a3 addObject:@"THPageLayerAndSubviewNoHitViewAccessibility"];
}

- (id)canvasViewDescription
{
  return THAccessibilityLocalizedString(@"canvas");
}

- (BOOL)supportsCharts
{
  return 0;
}

- (BOOL)supportsTableEditing
{
  return 0;
}

- (void)performExtraValidation
{
  v657.receiver = self;
  v657.super_class = (Class)THAccessibility;
  [(TSAccessibility *)&v657 performExtraValidation];
  __TSAccessibilityValidateInstanceMethodComplete(@"UIBarButtonItem", @"view", "@", v2, v3, v4, v5, v6, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"NSObject", @"_accessibilityEquivalenceTag", "@", v7, v8, v9, v10, v11, 0);
  __TSAccessibilityValidateIsKindOfClass(@"THBookViewController", @"UIViewController");
  __TSAccessibilityValidateInstanceMethodComplete(@"THBookViewController", @"applyAppearanceStyle:", "v", v12, v13, v14, v15, v16, "q");
  __TSAccessibilityValidateInstanceMethodComplete(@"THBookViewController", @"bookmarkToolbarButton", "@", v17, v18, v19, v20, v21, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THBookViewController", @"buyButtonItem", "@", v22, v23, v24, v25, v26, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THBookViewController", @"closeButton", "@", v27, v28, v29, v30, v31, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THBookViewController", @"closeTOCButton", "@", v32, v33, v34, v35, v36, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THBookViewController", @"displaySettingsToolbarButton", "@", v37, v38, v39, v40, v41, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THBookViewController", @"documentViewController", "@", v42, v43, v44, v45, v46, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THBookViewController", @"hideGlossaryWithDestinationViewController:", "v", v47, v48, v49, v50, v51, "@");
  __TSAccessibilityValidateInstanceMethodComplete(@"THBookViewController", @"isTOCVisible", "B", v52, v53, v54, v55, v56, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THBookViewController", @"p_applyAccessibilityLabelForButton:withImageNamed:", "v", v57, v58, v59, v60, v61, "@");
  __TSAccessibilityValidateInstanceMethodComplete(@"THBookViewController", @"p_popoverPassthroughViews", "@", v62, v63, v64, v65, v66, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THBookViewController", @"p_selectedTocViewController", "@", v67, v68, v69, v70, v71, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THBookViewController", @"p_showDVC", "v", v72, v73, v74, v75, v76, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THBookViewController", @"p_showDVCAnimated:withLink:", "v", v77, v78, v79, v80, v81, "B");
  __TSAccessibilityValidateInstanceMethodComplete(@"THBookViewController", @"searchToolbarButton", "@", v82, v83, v84, v85, v86, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THBookViewController", @"theme", "@", v87, v88, v89, v90, v91, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THBookViewController", @"toolbarController", "@", v92, v93, v94, v95, v96, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THChapterBrowserController", @"chapterViewController", "@", v97, v98, v99, v100, v101, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THChapterBrowserController", @"delegate", "@", v102, v103, v104, v105, v106, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THChapterBrowserController", @"followLink:", "B", v107, v108, v109, v110, v111, "@");
  __TSAccessibilityValidateInstanceMethodComplete(@"THChapterBrowserController", @"nextChapterViewController", "@", v112, v113, v114, v115, v116, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THChapterBrowserController", @"p_resetPagesScrollViewAndCapThumbCount:firstVisibleRelativePage:resetContentOffset:", "v", v117, v118, v119, v120, v121, "B");
  __TSAccessibilityValidateInstanceMethodComplete(@"THChapterBrowserController", @"previousChapterViewController", "@", v122, v123, v124, v125, v126, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THChapterBrowserScrubbablePageControl", @"p_updateWithNewPageIndex:animated:", "v", v127, v128, v129, v130, v131, "Q");
  __TSAccessibilityValidateInstanceMethodComplete(@"THChapterBrowserScrubbablePageControl", @"currentPage", "Q", v132, v133, v134, v135, v136, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THChapterBrowserScrubbablePageControl", @"firstDotSpecialRendering", "B", v137, v138, v139, v140, v141, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THChapterBrowserScrubbablePageControl", @"numberOfPages", "Q", v142, v143, v144, v145, v146, 0);
  __TSAccessibilityValidateIvar(@"THChapterViewController", "mDelegate");
  __TSAccessibilityValidateInstanceMethodComplete(@"THChapterViewController", @"chapterIndex", "Q", v147, v148, v149, v150, v151, 0);
  __TSAccessibilityValidateIsKindOfClass(@"THDocumentViewController", @"TSADocumentViewController");
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentViewController", @"activeSectionController", "@", v152, v153, v154, v155, v156, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentViewController", @"anchorFromLink:", "@", v157, v158, v159, v160, v161, "@");
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentViewController", @"canvasScrollView", "@", v162, v163, v164, v165, v166, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentViewController", @"canvasViewController", "@", v167, v168, v169, v170, v171, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentViewController", @"currentAbsolutePageIndex", "Q", v172, v173, v174, v175, v176, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentViewController", @"currentChapter", "Q", v177, v178, v179, v180, v181, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentViewController", @"documentRoot", "@", v182, v183, v184, v185, v186, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentViewController", @"expandedViewController", "@", v187, v188, v189, v190, v191, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentViewController", @"followLink:", "B", v192, v193, v194, v195, v196, "@");
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentViewController", @"hideToolbarAnimated:", "v", v197, v198, v199, v200, v201, "B");
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentViewController", @"hideToolbarAnimated:", "v", v202, v203, v204, v205, v206, "B");
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentViewController", @"inFlowMode", "B", v207, v208, v209, v210, v211, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentViewController", @"interactiveCanvasControllerDidStopScrolling:", "v", v212, v213, v214, v215, v216, "@");
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentViewController", @"leftOverscrollView", "@", v217, v218, v219, v220, v221, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentViewController", @"leftOverscrollView", "@", v222, v223, v224, v225, v226, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentViewController", @"p_horizontalOverscrollPreviousChapter", "v", v227, v228, v229, v230, v231, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentViewController", @"p_horizontalOverscrollNextChapter", "v", v232, v233, v234, v235, v236, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentViewController", @"p_pageLeft", "v", v237, v238, v239, v240, v241, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentViewController", @"p_pageRight", "v", v242, v243, v244, v245, v246, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentViewController", @"p_updateVisibleInfosWithPaddingOptions:force:", "v", v247, v248, v249, v250, v251, "i");
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentViewController", @"p_verticalOverscrollPreviousChapter", "v", v252, v253, v254, v255, v256, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentViewController", @"p_verticalOverscrollNextChapter", "v", v257, v258, v259, v260, v261, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentViewController", @"p_voiceOverStatusDidChange", "v", v262, v263, v264, v265, v266, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentViewController", @"rightOverscrollView", "@", v267, v268, v269, v270, v271, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentViewController", @"rightOverscrollView", "@", v272, v273, v274, v275, v276, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THBookViewController", @"showSearchPopoverFromButton:", "v", v277, v278, v279, v280, v281, "@");
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentViewController", @"showToolbarAnimated:", "v", v282, v283, v284, v285, v286, "B");
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentViewController", @"showToolbarAnimated:", "v", v287, v288, v289, v290, v291, "B");
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentViewController", @"viewDidLoad", "v", v292, v293, v294, v295, v296, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THDocumentViewController", @"viewDidUnload", "v", v297, v298, v299, v300, v301, 0);
  __TSAccessibilityValidateIsKindOfClass(@"THiOSIntroMediaViewController", @"UIViewController");
  __TSAccessibilityValidateInstanceMethodComplete(@"THiOSIntroMediaViewController", @"p_isImage", "B", v302, v303, v304, v305, v306, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THiOSIntroMediaViewController", @"p_nextPage", "v", v307, v308, v309, v310, v311, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THMultiLineLabel", @"text", "@", v312, v313, v314, v315, v316, 0);
  __TSAccessibilityValidateIvarType(@"THNoteCardsController", "_noteCardsView", "UIView");
  __TSAccessibilityValidateIvarType(@"THPageThumbnailView", "mPageNumberView", "THPageNumberView");
  __TSAccessibilityValidateInstanceMethodComplete(@"THPageThumbnailView", @"pageIndex", "Q", v317, v318, v319, v320, v321, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THPageNumberView", @"isCurrentPage", "B", v322, v323, v324, v325, v326, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THPageNumberView", @"label", "@", v327, v328, v329, v330, v331, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THPageNumberView", @"mode", "i", v332, v333, v334, v335, v336, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THPageNumberView", @"p_updatePageString", "v", v337, v338, v339, v340, v341, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THPageNumberView", @"setPageNumberText:", "v", v342, v343, v344, v345, v346, "@");
  __TSAccessibilityValidateInstanceMethodComplete(@"THToolbarController", @"delegate", "@", v347, v348, v349, v350, v351, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THToolbarController", @"setToolbarHidden:animated:duration:completion:", "v", v352, v353, v354, v355, v356, "B");
  __TSAccessibilityValidateIsKindOfClass(@"THWPEditingController", @"TSWPEditingController");
  __TSAccessibilityValidateInstanceMethodComplete(@"THWPEditingController", @"canPerformEditorAction:withSender:", "i", v357, v358, v359, v360, v361, ":");
  __TSAccessibilityValidateInstanceMethodComplete(@"THWPEditingController", @"editorCanHideEditMenu", "B", v362, v363, v364, v365, v366, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWPEditingController", @"extraMenuItems", "@", v367, v368, v369, v370, v371, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWPEditingController", @"shouldShowEditMenu", "B", v372, v373, v374, v375, v376, 0);
  __TSAccessibilityValidateIsKindOfClass(@"THiOSStudyViewController", @"UIViewController");
  __TSAccessibilityValidateInstanceMethodComplete(@"THiOSStudyViewController", @"done:", "v", v377, v378, v379, v380, v381, "@");
  __TSAccessibilityValidateIvarType(@"THiOSStudyViewController", "_noteCardsController", "THNoteCardsController");
  __TSAccessibilityValidateInstanceMethodComplete(@"THiOSStudyViewController", @"p_animateTransitionInWithCompletion:", "v", v382, v383, v384, v385, v386, "@?");
  __TSAccessibilityValidateIvarType(@"THNoteCardsController", "_noteCardsView", "UIView");
  __TSAccessibilityValidateInstanceMethodComplete(@"THNoteCardsController", @"animateBottomCardToTopInDirection:", "v", v387, v388, v389, v390, v391, "{CGPoint=dd}");
  __TSAccessibilityValidateInstanceMethodComplete(@"THNoteCardsController", @"animateTopCardToBottomInDirection:", "v", v392, v393, v394, v395, v396, "{CGPoint=dd}");
  __TSAccessibilityValidateInstanceMethodComplete(@"THNoteCardsController", @"detachFromView:", "v", v397, v398, v399, v400, v401, "@");
  __TSAccessibilityValidateInstanceMethodComplete(@"THNoteCardsController", @"p_handleDelayedCardUpdate", "v", v402, v403, v404, v405, v406, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THNoteCardsController", @"p_noteCardsForInfos:", "@", v407, v408, v409, v410, v411, "@");
  __TSAccessibilityValidateInstanceMethodComplete(@"THNoteCardsController", @"p_topNoteCard", "@", v412, v413, v414, v415, v416, 0);
  __TSAccessibilityValidateIvarType(@"THNoteCardLayer", "_delegate", "<THNoteCardLayerDelegate>");
  __TSAccessibilityValidateInstanceMethodComplete(@"THNoteCardLayer", @"frontLayer", "@", v417, v418, v419, v420, v421, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THNoteCardLayer", @"isBottomCard", "B", v422, v423, v424, v425, v426, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THNoteCardLayer", @"isFlipped", "B", v427, v428, v429, v430, v431, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THNoteCardLayer", @"isTopCard", "B", v432, v433, v434, v435, v436, 0);
  __TSAccessibilityValidateIsKindOfClass(@"THNotesDetailTableViewCell", @"UITableViewCell");
  __TSAccessibilityValidateInstanceMethodComplete(@"THNotesDetailTableViewCell", @"tableViewCellController", "@", v437, v438, v439, v440, v441, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THNotesDetailTableViewCellController", @"annotation", "@", v442, v443, v444, v445, v446, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THNotesDetailTableViewCellController", @"dateLabel", "@", v447, v448, v449, v450, v451, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THNotesDetailTableViewCellController", @"populateWithAnnotation:cellWidth:highlightLayer:highlightTextFrame:editingHighlightLayer:pageNumberString:topAdjustment:showDivider:", "v", v452, v453, v454, v455, v456, "@");
  __TSAccessibilityValidateInstanceMethodComplete(@"THNotesDetailTableViewCellController", @"returnToBook", "@", v457, v458, v459, v460, v461, 0);
  __TSAccessibilityValidateIvarType(@"THNotesDetailTableViewController", "mSelectedNotes", "NSMutableDictionary");
  __TSAccessibilityValidateInstanceMethodComplete(@"THNotesDetailTableViewController", @"deleteSelectedNotes", "v", v462, v463, v464, v465, v466, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THNotesDetailTableViewController", @"deselectAllNotes", "v", v467, v468, v469, v470, v471, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THNotesDetailTableViewController", @"notesDetailTableViewHeaderView:selected:", "v", v472, v473, v474, v475, v476, "@");
  __TSAccessibilityValidateInstanceMethodComplete(@"THNotesDetailTableViewController", @"selectAllNotes", "B", v477, v478, v479, v480, v481, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THNotesDetailTableViewController", @"tableView", "@", v482, v483, v484, v485, v486, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THNotesDetailTableViewController", @"tableView:didDeselectRowAtIndexPath:", "v", v487, v488, v489, v490, v491, "@");
  __TSAccessibilityValidateInstanceMethodComplete(@"THNotesDetailTableViewController", @"tableView:didSelectRowAtIndexPath:", "v", v492, v493, v494, v495, v496, "@");
  __TSAccessibilityValidateInstanceMethodComplete(@"THNotesDetailTableViewHeaderView", @"cellContentView", "@", v497, v498, v499, v500, v501, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THNotesDetailTableViewHeaderView", @"editing", "B", v502, v503, v504, v505, v506, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THNotesDetailTableViewHeaderView", @"selected", "B", v507, v508, v509, v510, v511, 0);
  __TSAccessibilityValidateIvarType(@"THNotesSidebarTableCell", "chapterLabel", "UILabel");
  __TSAccessibilityValidateIvarType(@"THNotesSidebarTableCell", "chapterName", "UILabel");
  __TSAccessibilityValidateIvarType(@"THNotesSidebarTableCell", "countLabel", "UILabel");
  __TSAccessibilityValidateIsKindOfClass(@"THNotesViewController", @"UIViewController");
  __TSAccessibilityValidateInstanceMethodComplete(@"THNotesViewController", @"bookViewController", "@", v512, v513, v514, v515, v516, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THNotesViewController", @"isViewLoaded", "B", v517, v518, v519, v520, v521, 0);
  __TSAccessibilityValidateIsKindOfClass(@"THNotesViewControllerPad", @"UIViewController");
  __TSAccessibilityValidateIvarType(@"THNotesViewControllerPad", "_actionButtonItem", "UIBarButtonItem");
  __TSAccessibilityValidateIvarType(@"THNotesViewControllerPad", "_selectButtonItem", "UIBarButtonItem");
  __TSAccessibilityValidateInstanceMethodComplete(@"THNotesViewControllerPad", @"handleAction:", "v", v522, v523, v524, v525, v526, "@");
  __TSAccessibilityValidateInstanceMethodComplete(@"THNotesViewControllerPad", @"handleStudy:", "v", v527, v528, v529, v530, v531, "@");
  __TSAccessibilityValidateInstanceMethodComplete(@"THNotesViewControllerPad", @"p_configureToolbarsForEditing:collapsed:", "v", v532, v533, v534, v535, v536, "B");
  __TSAccessibilityValidateInstanceMethodComplete(@"THNotesViewControllerPad", @"p_returnToOriginalViewController", "v", v537, v538, v539, v540, v541, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWGutterRep", @"pressableHandler", "@", v542, v543, v544, v545, v546, 0);
  __TSAccessibilityValidateIsKindOfClass(@"THWiOSExpandedViewController", @"UIViewController");
  __TSAccessibilityValidateInstanceMethodComplete(@"THWiOSExpandedViewController", @"adornmentController", "@", v547, v548, v549, v550, v551, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWiOSExpandedViewController", @"animationControllerDidPresentPostCommit:", "v", v552, v553, v554, v555, v556, "@");
  __TSAccessibilityValidateInstanceMethodComplete(@"THWiOSExpandedViewController", @"cvc", "@", v557, v558, v559, v560, v561, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWiOSExpandedViewController", @"dismiss", "v", v562, v563, v564, v565, v566, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWiOSExpandedViewController", @"expandedRepControllerState", "i", v567, v568, v569, v570, v571, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWiOSExpandedViewController", @"icc", "@", v572, v573, v574, v575, v576, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWPressableRepGestureTargetHandler", @"p_invokeAction", "v", v577, v578, v579, v580, v581, 0);
  __TSAccessibilityValidateInstanceMethod(@"CAKPFSession", @"currentEvent");
  __TSAccessibilityValidateInstanceMethod(@"CAKPFPlayerController", @"session");
  __TSAccessibilityValidateInstanceMethod(@"CAKPFPlayerController", @"prepareWithEndShowHandler:");
  __TSAccessibilityValidateInstanceMethod(@"CAKPFPlayerController", @"gotoPreviousEvent");
  __TSAccessibilityValidateInstanceMethod(@"CAKPFPlayerController", @"p_gotoEventIndex:skipBreadCrumb:shouldAutoPlay:");
  __TSAccessibilityValidateInstanceMethod(@"CAKPFPlayerController", @"gotoPreviousSlide");
  __TSAccessibilityValidateInstanceMethod(@"CAKPFPlayerController", @"p_triggerNextEvent");
  __TSAccessibilityValidateInstanceMethod(@"KPFEvent", @"p_rectFromDictionary:");
  __TSAccessibilityValidateInstanceMethod(@"THApplePubAssetPlugin", @"currentBook");
  __TSAccessibilityValidateInstanceMethodComplete(@"THInteractiveCanvasController", @"hitRep:allowsAllReps:", "@", v582, v583, v584, v585, v586, "{CGPoint=dd}");
  __TSAccessibilityValidateInstanceMethod(@"THBookDescription", @"language");
  __TSAccessibilityValidateInstanceMethod(@"THBookmarkMenuPopoverViewController", @"tableView:didSelectRowAtIndexPath:");
  __TSAccessibilityValidateInstanceMethod(@"THBookmarkMenuTableViewCell", @"bookmarkTitleLabel");
  __TSAccessibilityValidateInstanceMethod(@"THBookmarkMenuTableViewCell", @"pageNumberLabel");
  __TSAccessibilityValidateInstanceMethod(@"THBookViewController", @"bookDescription");
  __TSAccessibilityValidateInstanceMethod(@"THBookViewController", @"bookmarkToolbarButton");
  __TSAccessibilityValidateInstanceMethodComplete(@"THBookViewController", @"chapterBrowserController:tocTileModelAtIndex:", "@", v587, v588, v589, v590, v591, "@");
  __TSAccessibilityValidateInstanceMethod(@"THBookViewController", @"updateBookmarkButton");
  __TSAccessibilityValidateInstanceMethod(@"THBookViewController", @"viewDidAppear:");
  __TSAccessibilityValidateInstanceMethod(@"THBookViewController", @"toolbarController");
  __TSAccessibilityValidateInstanceMethod(@"THBookViewController", @"hideToolbarAnimated:");
  __TSAccessibilityValidateInstanceMethod(@"THBookViewController", @"shouldAutohideNavigationBar");
  __TSAccessibilityValidateInstanceMethod(@"THBookViewController", @"showTOC");
  __TSAccessibilityValidateInstanceMethod(@"THBookViewController", @"chapterCountForChapterBrowserController:");
  __TSAccessibilityValidateInstanceMethod(@"THBookViewController", @"chapterBrowserController:tocTileModelAtIndex:");
  __TSAccessibilityValidateInstanceMethod(@"THBookViewController", @"showFullscreenNotesView:");
  __TSAccessibilityValidateInstanceMethod(@"THBookViewController", @"hideFullscreenNotesView:andSearchForText:animated:completion:");
  __TSAccessibilityValidateInstanceMethod(@"THBookViewController", @"p_showGlossary");
  __TSAccessibilityValidateInstanceMethod(@"THBookViewController", @"isGlossaryVisible");
  __TSAccessibilityValidateInstanceMethodComplete(@"THBookViewController", @"glossaryViewController", "@", v592, v593, v594, v595, v596, 0);
  __TSAccessibilityValidateInstanceMethod(@"THBookViewController", @"tocGlossaryButton");
  __TSAccessibilityValidateInstanceMethod(@"THChapterBrowserController", @"chapterIndex");
  __TSAccessibilityValidateInstanceMethod(@"THChapterBrowserController", @"setChapterIndex:");
  __TSAccessibilityValidateInstanceMethod(@"THChapterBrowserController", @"chapterPageControl");
  __TSAccessibilityValidateInstanceMethod(@"THChapterBrowserController", @"backgroundScrollView");
  __TSAccessibilityValidateInstanceMethod(@"THChapterBrowserController", @"setBackgroundScrollView:");
  __TSAccessibilityValidateInstanceMethod(@"THChapterBrowserController", @"pagesScrollView");
  __TSAccessibilityValidateInstanceMethod(@"THChapterBrowserController", @"setPagesScrollView:");
  __TSAccessibilityValidateInstanceMethod(@"THChapterBrowserController", @"pagesScrollView");
  __TSAccessibilityValidateInstanceMethod(@"THChapterBrowserController", @"introMediaControllerIsActive");
  __TSAccessibilityValidateInstanceMethod(@"THChapterBrowserController", @"introMediaControllerShouldAdvancePast:");
  __TSAccessibilityValidateInstanceMethod(@"THChapterBrowserController", @"takeChapterIndexFrom:");
  __TSAccessibilityValidateInstanceMethod(@"THChapterBrowserController", @"relinquishIntroMediaViewController");
  __TSAccessibilityValidateInstanceMethod(@"THChapterBrowserController", @"p_backgroundScrollingDidEnd");
  __TSAccessibilityValidateInstanceMethod(@"THChapterBrowserController", @"p_pageThumbScrollingDidEnd");
  __TSAccessibilityValidateInstanceMethod(@"THChapterBrowserController", @"p_releaseOutlets");
  __TSAccessibilityValidateInstanceMethod(@"THChapterBrowserController", @"hasIntroPage");
  __TSAccessibilityValidateInstanceMethod(@"THChapterBrowserController", @"p_thumbnailAnimationDidStopWithContext:");
  __TSAccessibilityValidateInstanceMethod(@"THChapterBrowserController", @"p_updatePageThumbnails:");
  __TSAccessibilityValidateInstanceMethod(@"THChapterBrowserController", @"scrollViewDidEndDragging:willDecelerate:");
  __TSAccessibilityValidateInstanceMethod(@"THChapterBrowserController", @"setIntroMediaViewController:");
  __TSAccessibilityValidateInstanceMethod(@"THChapterBrowserController", @"setIntroMediaViewController:showIt:");
  __TSAccessibilityValidateInstanceMethod(@"THChapterBrowserController", @"willTransitionFromChapterIndex:");
  __TSAccessibilityValidateInstanceMethod(@"THBookViewController", @"showToolbarAnimated:");
  __TSAccessibilityValidateInstanceMethod(@"THHighlightControllerCachedAnnotation", @"annotation");
  __TSAccessibilityValidateInstanceMethod(@"THPageThumbnailView", @"initWithFrame:isFirstThumbnail:delegate:");
  __TSAccessibilityValidateInstanceMethod(@"THPageThumbnailView", @"setPageNumberText:");
  __TSAccessibilityValidateInstanceMethod(@"THPopoverController", @"presentPopoverFromRect:inView:permittedArrowDirections:animated:");
  __TSAccessibilityValidateInstanceMethod(@"THPopoverController", @"dismissPopoverAnimated:");
  __TSAccessibilityValidateInstanceMethod(@"UIButton", @"_accessibilityImagePath");
  __TSAccessibilityValidateIsKindOfClass(@"THFlowTOCViewController", @"THTOCViewController");
  __TSAccessibilityValidateInstanceMethod(@"THFlowTOCViewController", @"introMediaControllerShouldAdvancePast:");
  __TSAccessibilityValidateInstanceMethod(@"THFlowTOCViewController", @"accessoryTapped:");
  __TSAccessibilityValidateInstanceMethod(@"THFlowTOCViewController", @"backgroundButton");
  __TSAccessibilityValidateInstanceMethodComplete(@"THFlowTOCViewController", @"headerImageViews", "@", v597, v598, v599, v600, v601, 0);
  __TSAccessibilityValidateInstanceMethod(@"THTOCTileModel", @"frontTitleText");
  __TSAccessibilityValidateInstanceMethod(@"THTOCTileModel", @"portraitEntries");
  __TSAccessibilityValidateInstanceMethod(@"THTOCTileModel", @"tinyThumbs");
  __TSAccessibilityValidateInstanceMethod(@"THTOCTileModelEntry", @"sectionIdentifier");
  __TSAccessibilityValidateInstanceMethod(@"THTOCViewController", @"delegate");
  __TSAccessibilityValidateInstanceMethodComplete(@"THTOCViewController", @"introMediaControllerIsActive", "B", v602, v603, v604, v605, v606, 0);
  __TSAccessibilityValidateInstanceMethod(@"THToolbar", @"centerItem");
  __TSAccessibilityValidateInstanceMethod(@"THToolbarController", @"setCenterTitle:");
  __TSAccessibilityValidateInstanceMethod(@"THToolbarController", @"setToolbarHidden:");
  __TSAccessibilityValidateInstanceMethod(@"THToolbarController", @"toolbar");
  __TSAccessibilityValidateIsKindOfClass(@"THWDetailSlider", @"UISlider");
  __TSAccessibilityValidateIvarType(@"THWDetailSlider", "_canCommit", "B");
  __TSAccessibilityValidateIvarType(@"THWDetailSlider", "_isTracking", "B");
  __TSAccessibilityValidateIvarType(@"THWDetailSlider", "_needsCommit", "B");
  __TSAccessibilityValidateInstanceMethodComplete(@"THWDetailSlider", @"availableDuration", "d", v607, v608, v609, v610, v611, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWDetailSlider", @"_setValueWhileTracking:animated:", "v", v612, v613, v614, v615, v616, "f");
  __TSAccessibilityValidateInstanceMethod(@"THWPHighlightController", @"annotationCache");
  __TSAccessibilityValidateInstanceMethodComplete(@"THWPHighlightController", @"highlightAtCanvasPoint:", "@", v617, v618, v619, v620, v621, "{CGPoint=dd}");
  __TSAccessibilityValidateInstanceMethod(@"THWPHighlightController", @"marginNotesController");
  __TSAccessibilityValidateInstanceMethod(@"THWPHighlightController", @"parentRep");
  __TSAccessibilityValidateInstanceMethod(@"THWPHighlightController", @"p_addHighlight:forCachedAnnotation:");
  __TSAccessibilityValidateInstanceMethod(@"THWPHighlightController", @"p_clearAnnotationCache");
  __TSAccessibilityValidateInstanceMethod(@"THWPHighlightController", @"p_removeCachedAnnotation:");
  __TSAccessibilityValidateInstanceMethod(@"THWPHighlightController", @"p_removeHighlightForCachedAnnotation:");
  __TSAccessibilityValidateInstanceMethod(@"THWPHighlightController", @"p_removeNoteForCachedAnnotation:");
  __TSAccessibilityValidateInstanceMethod(@"THWPHighlightController", @"p_repRectForHighlight:");
  __TSAccessibilityValidateInstanceMethod(@"THWPHighlightController", @"p_setLineProperties:fromRange:isUnderline:");
  __TSAccessibilityValidateInstanceMethodComplete(@"THWPHighlightController", @"p_showEditorForHighlight:", "v", v622, v623, v624, v625, v626, "@");
  __TSAccessibilityValidateInstanceMethod(@"THWPHighlightController", @"p_updateHighlight:toRange:rect:");
  __TSAccessibilityValidateInstanceMethod(@"THWPHighlightController", @"p_updateMarginNoteForCachedAnnotation:");
  __TSAccessibilityValidateInstanceMethod(@"THWPHighlightController", @"p_updateMarginNoteForHighlight:");
  __TSAccessibilityValidateInstanceMethod(@"THWPHighlightController", @"updateCachedAnnotations");
  __TSAccessibilityValidateInstanceMethodComplete(@"THWPRep", @"highlightController", "@", v627, v628, v629, v630, v631, 0);
  __TSAccessibilityValidateInstanceMethod(@"THWPRep", @"marginNotesController");
  __TSAccessibilityValidateInstanceMethod(@"THWPRep", @"setupMarginNotesControllerForHighlightController:");
  __TSAccessibilityValidateInstanceMethod(@"TSDCanvasView", @"enclosingScrollView");
  __TSAccessibilityValidateInstanceMethodComplete(@"TSDiOSCanvasViewController", @"canvasView", "@", v632, v633, v634, v635, v636, 0);
  __TSAccessibilityValidateInstanceMethod(@"NSObject", @"accessibilityCompareGeometry:");
  __TSAccessibilityValidateInstanceMethod(@"TSWPopoverController", @"presentPopoverFromRect:inView:viewBounds:permittedArrowDirections:displayMode:animated:");
  __TSAccessibilityValidateInstanceMethod(@"TSWPopoverController", @"dismissPopoverAnimated:");
  __TSAccessibilityValidateInstanceMethod(@"TSWPopoverController", @"p_didFade");
  __TSAccessibilityValidateInstanceMethod(@"TSWReviewChoiceDescription", @"choiceAlternateText");
  __TSAccessibilityValidateInstanceMethod(@"TSWReviewChoiceDescription", @"choiceTargetAlternateText");
  __TSAccessibilityValidateInstanceMethod(@"TSWReviewChoiceDescription", @"choiceContentType");
  __TSAccessibilityValidateInstanceMethod(@"TSWReviewChoiceDescription", @"choiceContentType");
  __TSAccessibilityValidateInstanceMethod(@"TSWReviewQuestionDescription", @"questionPromptAlternateText");
  __TSAccessibilityValidateInstanceMethod(@"TSWReviewQuestionDescription", @"questionReferenceContentAlternateText");
  __TSAccessibilityValidateInstanceMethod(@"TSWReviewQuestionDescription", @"choiceAtIndex:");
  __TSAccessibilityValidateInstanceMethod(@"TSWReviewQuestionDescription", @"numberOfChoices");
  __TSAccessibilityValidateInstanceMethod(@"TSWSelfContainedWPViewController", @"icc");
  __TSAccessibilityValidateInstanceMethod(@"TSWSelfContainedWPViewController", @"layoutWithFrame:");
  __TSAccessibilityValidateInstanceMethodComplete(@"TSWSelfContainedWPViewController", @"interactiveCanvasControllerDidLayout:", "v", v637, v638, v639, v640, v641, "@");
  __TSAccessibilityValidateInstanceMethod(@"TSWSelfContainedWPViewController", @"storage");
  __TSAccessibilityValidateInstanceMethod(@"THGlossaryDefinitionsViewController", @"displayedEntry");
  __TSAccessibilityValidateInstanceMethod(@"THGlossaryDefinitionsViewController", @"glossaryViewController");
  __TSAccessibilityValidateInstanceMethod(@"THGlossaryDefinitionsViewController", @"loadView");
  __TSAccessibilityValidateInstanceMethod(@"THGlossaryDefinitionsViewController", @"p_currentEntryIndex");
  __TSAccessibilityValidateInstanceMethod(@"THGlossaryDefinitionsViewController", @"p_entryDidLoad:");
  __TSAccessibilityValidateInstanceMethod(@"THGlossaryEntryInfo", @"headerInfo");
  __TSAccessibilityValidateInstanceMethod(@"THGlossaryEntryRep", @"childRepsForHitTesting");
  __TSAccessibilityValidateInstanceMethod(@"THGlossaryEntryRep", @"p_newTitleLayer");
  __TSAccessibilityValidateInstanceMethod(@"THGlossaryEntryViewController", @"loading");
  __TSAccessibilityValidateInstanceMethod(@"THGlossaryEntryViewController", @"loadView");
  __TSAccessibilityValidateInstanceMethod(@"THGlossaryTermsViewController", @"tableView:willSelectRowAtIndexPath:");
  __TSAccessibilityValidateInstanceMethod(@"THGlossaryTermsViewController", @"sectionIndexTitlesForTableView:");
  __TSAccessibilityValidateInstanceMethod(@"THGlossaryViewController", @"definitionsViewController");
  __TSAccessibilityValidateInstanceMethod(@"THGlossaryViewController", @"didScrollToEntry:");
  __TSAccessibilityValidateInstanceMethod(@"THGlossaryViewController", @"followGlossaryAnchor:");
  __TSAccessibilityValidateInstanceMethod(@"THModelGlossaryEntry", @"term");
  __TSAccessibilityValidateInstanceMethod(@"THModelGlossaryEntryBody", @"headerInfo");
  __TSAccessibilityValidateInstanceMethod(@"THModelGlossaryEntryFlushable", @"p_populate");
  __TSAccessibilityValidateInstanceMethod(@"THModelGlossaryEntryFlushable", @"body");
  __TSAccessibilityValidateInstanceMethod(@"THModelLink", @"initWithTarget:context:");
  __TSAccessibilityValidateInstanceMethod(@"THFlowTOCTableViewCell", @"openCloseButton");
  __TSAccessibilityValidateInstanceMethod(@"THFlowTOCTableViewCell", @"p_setupContentView");
  __TSAccessibilityValidateInstanceMethod(@"THNoteCardLayer", @"isFlipped");
  __TSAccessibilityValidateInstanceMethod(@"THNoteCardLayer", @"isTopCard");
  __TSAccessibilityValidateInstanceMethod(@"THNoteCardLayer", @"isBottomCard");
  __TSAccessibilityValidateInstanceMethod(@"AEAnnotationPopoverViewController", @"presentFromRect:view:");
  __TSAccessibilityValidateInstanceMethod(@"AEAnnotationPopoverViewController", @"hide");
  __TSAccessibilityValidateInstanceMethod(@"AEHighlight", @"annotation");
  __TSAccessibilityValidateInstanceMethod(@"AEHighlightColorEditorController", @"p_removeAnnotation:");
  __TSAccessibilityValidateInstanceMethod(@"AEMarginNote", @"annotation");
  __TSAccessibilityValidateInstanceMethod(@"AEMarginNotesController", @"layers");
  __TSAccessibilityValidateInstanceMethod(@"AENotePopoverEditorController", @"p_didShow");
  __TSAccessibilityValidateInstanceMethod(@"AENotePopoverEditorController", @"noteEditorViewController");
  __TSAccessibilityValidateInstanceMethod(@"AENoteEditorViewController", @"textView");
  __TSAccessibilityValidateInstanceMethod(@"KPFDocument", @"newEventAtIndex:");
  __TSAccessibilityValidateInstanceMethod(@"THWIOSMovieRep", @"movieInfo");
  __TSAccessibilityValidateInstanceMethodComplete(@"THWIOSMovieRep", @"control:repWasAdded:", "v", v642, v643, v644, v645, v646, "@");
  __TSAccessibilityValidateInstanceMethodComplete(@"THWIOSMovieRep", @"isPlaying", "B", v647, v648, v649, v650, v651, 0);
  __TSAccessibilityValidateInstanceMethodComplete(@"THWIOSMovieRep", @"play", "v", v652, v653, v654, v655, v656, 0);
  __TSAccessibilityValidateIvar(@"THChapterBrowserController", "mPullThroughInProgress");
  __TSAccessibilityValidateIvar(@"THLabelWithWordHighlights", "mText");
  __TSAccessibilityValidateIvar(@"THGlossaryDefinitionsViewController", "mEntryViewControllers");
  __TSAccessibilityValidateIvar(@"THGlossaryDefinitionsViewController", "mScrollView");
  __TSAccessibilityValidateIvar(@"THGlossaryTermTableViewCell", "mLabelWithHighlights");
  __TSAccessibilityValidateIvarType(@"THGlossaryEntryViewController", "mICC", "THGlossaryInteractiveCanvasController");
  __TSAccessibilityValidateIvar(@"THGlossaryEntryViewController", "mInfo");
  __TSAccessibilityValidateIvar(@"THGlossaryEntryViewController", "mScrollView");
  __TSAccessibilityValidateIvar(@"KPFEvent", "mEventDictionary");
  __TSAccessibilityValidateIvar(@"TSWPRep", "_selectionParagraphBorderLayer");
  __TSAccessibilityValidateIvar(@"TSWPRep", "_caretLayer");
  __TSAccessibilityValidateIvar(@"TSWPRep", "_pulseArrayController");
  __TSAccessibilityValidateIvar(@"TSWPRep", "_pulseArrayController");
  __TSAccessibilityValidateIvar(@"CAKPFSession", "mCurrentEventIndex");
  __TSAccessibilityValidateIvar(@"CAKPFSession", "mKPFDocument");
  __TSAccessibilityValidateProtocolMethod(@"TSDContainerRep", @"addAdditionalChildLayersToArray:", 1, 1);
  __TSAccessibilityValidateClass(@"BKAppDelegate");
  __TSAccessibilityValidateClassMethod(@"THApplePubAssetPlugin", @"sharedPlugin");
  __TSAccessibilityValidateIsKindOfClass(@"TSKDocumentRoot", @"TSPObject");
  __TSAccessibilityValidateIsKindOfClass(@"TSDiOSCanvasViewController", @"UIViewController");
  __TSAccessibilityValidateIsKindOfClass(@"TSWPopoverController", @"UIViewController");
  __TSAccessibilityValidateIsKindOfClass(@"THBodyRep", @"THWPRep");
  __TSAccessibilityValidateIsKindOfClass(@"THFlowBodyRep", @"THBodyRep");
  __TSAccessibilityValidateIsKindOfClass(@"THInteractiveCanvasController", @"TSDInteractiveCanvasController");
  __TSAccessibilityValidateIsKindOfClass(@"THChapterBrowserController", @"THTOCViewController");
  __TSAccessibilityValidateIsKindOfClass(@"THFlowTOCViewController", @"THTOCViewController");
  __TSAccessibilityValidateIsKindOfClass(@"THGlossaryInteractiveCanvasController", @"TSDInteractiveCanvasController");
  __TSAccessibilityValidateIsKindOfClass(@"THGlossaryDefinitionsViewController", @"UIViewController");
  __TSAccessibilityValidateIsKindOfClass(@"THGlossaryEntryViewController", @"UIViewController");
  __TSAccessibilityValidateIsKindOfClass(@"THGlossaryEntryFloatingRep", @"TSDContainerRep");
  __TSAccessibilityValidateIsKindOfClass(@"THTOCViewController", @"UIViewController");
  __TSAccessibilityValidateIsKindOfClass(@"THImageInfo", @"TSDImageInfo");
  __TSAccessibilityValidateIsKindOfClass(@"THImageRep", @"TSDImageRep");
  __TSAccessibilityValidateIsKindOfClass(@"THModelGlossaryEntryAnchor", @"THModelNavigableAnchor");
  __TSAccessibilityValidateIsKindOfClass(@"THPageRep", @"TSDContainerRep");
  __TSAccessibilityValidateIsKindOfClass(@"THFlowPageRep", @"THPageRep");
  __TSAccessibilityValidateIsKindOfClass(@"THScrollView", @"TSKScrollView");
  __TSAccessibilityValidateIsKindOfClass(@"THScrollViewWithPassthrough", @"UIScrollView");
  __TSAccessibilityValidateIsKindOfClass(@"THSectionRep", @"TSDContainerRep");
  __TSAccessibilityValidateIsKindOfClass(@"THToolbar", @"UIToolbar");
  __TSAccessibilityValidateIsKindOfClass(@"THWPRep", @"TSWPRep");
  __TSAccessibilityValidateIsKindOfClass(@"THMarginNotesController", @"AEMarginNotesController");
  __TSAccessibilityValidateIsKindOfClass(@"IMApplication", @"UIApplication");
  __TSAccessibilityValidateIsKindOfClass(@"BKApplication", @"IMApplication");
  __TSAccessibilityValidateIsKindOfClass(@"TSWPEquationRep", @"TSDRep");
  __TSAccessibilityValidateInstanceMethod(@"TSWPEquationInfo", @"equation");
  __TSAccessibilityValidateInstanceMethod(@"EQKitMathMLMUnderover", @"schemataBase");
  __TSAccessibilityValidateInstanceMethod(@"EQKitMathMLMUnderover", @"schemataUnder");
  __TSAccessibilityValidateInstanceMethod(@"EQKitMathMLMUnderover", @"schemataOver");
  __TSAccessibilityValidateInstanceMethod(@"EQKitMathMLMOver", @"schemataBase");
  __TSAccessibilityValidateInstanceMethod(@"EQKitMathMLMOver", @"schemataUnder");
  __TSAccessibilityValidateInstanceMethod(@"EQKitMathMLMOver", @"schemataOver");
  __TSAccessibilityValidateInstanceMethod(@"EQKitMathMLMUnder", @"schemataBase");
  __TSAccessibilityValidateInstanceMethod(@"EQKitMathMLMUnder", @"schemataUnder");
  __TSAccessibilityValidateInstanceMethod(@"EQKitMathMLMUnder", @"schemataOver");
  __TSAccessibilityValidateInstanceMethod(@"EQKitMathMLMFraction", @"operatorCore");
  __TSAccessibilityValidateInstanceMethod(@"EQKitMathMLMToken", @"schemataTokenString");
  __TSAccessibilityValidateInstanceMethod(@"EQKitMathMLMToken", @"schemataFontStyling");
  __TSAccessibilityValidateInstanceMethod(@"EQKitMathMLMToken", @"scriptVariant");
  __TSAccessibilityValidateInstanceMethod(@"EQKitMathMLMOperator", @"operatorUnicharOrNul");
  __TSAccessibilityValidateInstanceMethod(@"EQKitMathMLMSuperscript", @"schemataKernel");
  __TSAccessibilityValidateInstanceMethod(@"EQKitMathMLMSuperscript", @"schemataSubscript");
  __TSAccessibilityValidateInstanceMethod(@"EQKitMathMLMSuperscript", @"schemataSuperscript");
  __TSAccessibilityValidateInstanceMethod(@"EQKitMathMLMSubscript", @"schemataKernel");
  __TSAccessibilityValidateInstanceMethod(@"EQKitMathMLMSubscript", @"schemataSubscript");
  __TSAccessibilityValidateInstanceMethod(@"EQKitMathMLMSubscript", @"schemataSuperscript");
  __TSAccessibilityValidateInstanceMethod(@"EQKitMathMLMSubsuperscript", @"schemataKernel");
  __TSAccessibilityValidateInstanceMethod(@"EQKitMathMLMSubsuperscript", @"schemataSubscript");
  __TSAccessibilityValidateInstanceMethod(@"EQKitMathMLMSubsuperscript", @"schemataSuperscript");
  __TSAccessibilityValidateInstanceMethod(@"EQKitMathMLMSqrt", @"schemataRadicand");
  __TSAccessibilityValidateInstanceMethod(@"EQKitMathMLMSqrt", @"schemataIndex");
  __TSAccessibilityValidateInstanceMethod(@"EQKitMathMLMRoot", @"schemataRadicand");
  __TSAccessibilityValidateInstanceMethod(@"EQKitMathMLMRoot", @"schemataIndex");
  __TSAccessibilityValidateIvarType(@"EQKitMathMLMRow", "mChildren", "NSArray");
  __TSAccessibilityValidateIvarType(@"EQKitMathMLUnaryNode", "mChild", "EQKitMathMLNode");
  __TSAccessibilityValidateIvarType(@"EQKitMathMLBinaryNode", "mFirst", "EQKitMathMLNode");
  __TSAccessibilityValidateIvarType(@"EQKitMathMLBinaryNode", "mSecond", "EQKitMathMLNode");
  __TSAccessibilityValidateIvarType(@"EQKitMathMLMAction", "mExpression", "EQKitMathMLNode");
  __TSAccessibilityValidateIvarType(@"EQKitMathMLMTable", "mChildren", "NSArray");
  __TSAccessibilityValidateIvarType(@"EQKitMathMLMTr", "mChildren", "NSArray");
  __TSAccessibilityValidateIvarType(@"EQKitMathMLMTd", "mChildren", "NSArray");
  __TSAccessibilityValidateIvarType(@"EQKitMathMLMLongDivision", "mStack", "EQKitMathMLMStack");
  __TSAccessibilityValidateIvarType(@"EQKitMathMLMLongDivision", "mDivisor", "EQKitMathMLNode");
  __TSAccessibilityValidateIvarType(@"EQKitMathMLMFenced", "mChildren", "NSArray");
  __TSAccessibilityValidateIvarType(@"EQKitMathMLMText", "mContent", "EQKitMathMLTokenContent");
  __TSAccessibilityValidateIvarType(@"EQKitMathMLTokenContent", "mChildren", "NSArray");
  __TSAccessibilityValidateIvarType(@"EQKitMathMLMStackRow", "mChildren", "NSArray");
  __TSAccessibilityValidateIvarType(@"EQKitMathMLMStackGroup", "mChildren", "NSArray");
  __TSAccessibilityValidateIvarType(@"EQKitMathMLMStackCarry", "mChildren", "NSArray");
  __TSAccessibilityValidateIvarType(@"EQKitMathMLMStack", "mChildren", "NSArray");
  __TSAccessibilityValidateIvarType(@"EQKitEquation", "mSource", "NSData");
  __TSAccessibilityValidateIvarType(@"EQKitMathMLMath", "mExpression", "EQKitMathMLNode");
  __TSAccessibilityValidateIsKindOfClass(@"EQKitMathMLMStyle", @"EQKitMathMLUnaryNode");
}

- (void)addExtraSafeCategoryNamesToCollection:(id)a3
{
  v4.receiver = self;
  v4.super_class = (Class)THAccessibility;
  -[TSAccessibility addExtraSafeCategoryNamesToCollection:](&v4, "addExtraSafeCategoryNamesToCollection:");
  [a3 addObject:@"THDocumentViewControllerAccessibility"];
  [a3 addObject:@"THCALayerAccessibility"];
  [a3 addObject:@"THUIAccessibilityElement"];
  [a3 addObject:@"THUIBarButtonItemAccessibility"];
  [a3 addObject:@"THUIButtonAccessibility"];
  [a3 addObject:@"THUIImageViewAccessibility"];
  [a3 addObject:@"THUIPopoverControllerAccessibility"];
  [a3 addObject:@"THUIScrollViewAccessibility"];
  [a3 addObject:@"THUISliderAccessibility"];
  [a3 addObject:@"THUITextViewAccessibility"];
  [a3 addObject:@"THUIViewAccessibility"];
  [a3 addObject:@"THWebAccessibilityObjectWrapper"];
  [a3 addObject:@"THNSObjectAccessibility"];
  [a3 addObject:@"THTSDMovieRepAccessibility"];
  [a3 addObject:@"THTSWPHyperlinkFieldAccessibility"];
  [a3 addObject:@"TSWPEquationRepAccessibility"];
  [a3 addObject:@"THAEAnnotationPopoverViewControllerAccessibility"];
  [a3 addObject:@"THAEHighlightColorEditorControllerAccessibility"];
  [a3 addObject:@"THAEMarginNotesControllerAccessibility"];
  [a3 addObject:@"THBodyRepAccessibility"];
  [a3 addObject:@"THBookmarkMenuPopoverViewControllerAccessibility"];
  [a3 addObject:@"THBookmarkMenuTableViewCellAccessibility"];
  [a3 addObject:@"THBookViewControllerAccessibility"];
  [a3 addObject:@"THChapterBrowserControllerAccessibility"];
  [a3 addObject:@"THChapterBrowserScrubbablePageControlAccessibility"];
  [a3 addObject:@"THChapterViewControllerAccessibility"];
  [a3 addObject:@"THFlowBodyRepAccessibility"];
  [a3 addObject:@"THFlowTOCTableViewCellAccessibility"];
  [a3 addObject:@"THFlowTOCViewControllerAccessibility"];
  [a3 addObject:@"THGlossaryDefinitionsViewControllerAccessibility"];
  [a3 addObject:@"THGlossaryEntryRepAccessibility"];
  [a3 addObject:@"THGlossaryTermsViewControllerAccessibility"];
  [a3 addObject:@"THGlossaryTermTableViewCellAccessibility"];
  [a3 addObject:@"THGlossaryViewControllerAccessibility"];
  [a3 addObject:@"THWGutterInfoAccessibility"];
  [a3 addObject:@"THWGutterRepAccessibility"];
  [a3 addObject:@"THInteractiveCanvasControllerAccessibility"];
  [a3 addObject:@"THiOSCanvasViewControllerAccessibility"];
  [a3 addObject:@"THiOSIntroMediaViewAccessibility"];
  [a3 addObject:@"THiOSIntroMediaViewControllerAccessibility"];
  [a3 addObject:@"THiOSStudyViewControllerAccessibility"];
  [a3 addObject:@"THLabelWithWordHighlightsAccessibility"];
  [a3 addObject:@"THModelGlossaryEntryFlushableAccessibility"];
  [a3 addObject:@"THMPVideoViewAccessibility"];
  [a3 addObject:@"THMultiLineLabelAccessibility"];
  [a3 addObject:@"THNoteCardLayerAccessibility"];
  [a3 addObject:@"THNoteCardsControllerAccessibility"];
  [a3 addObject:@"THNotesDetailTableViewCellAccessibility"];
  [a3 addObject:@"THNotesDetailTableViewCellControllerAccessibility"];
  [a3 addObject:@"THNotesDetailTableViewControllerAccessibility"];
  [a3 addObject:@"THNotesDetailTableViewHeaderViewAccessibility"];
  [a3 addObject:@"THNotesSidebarTableCellAccessibility"];
  [a3 addObject:@"THNotesViewControllerAccessibility"];
  [a3 addObject:@"THNotesViewControllerPadAccessibility"];
  [a3 addObject:@"THPageNumberViewAccessibility"];
  [a3 addObject:@"THPageThumbnailViewAccessibility"];
  [a3 addObject:@"THPopoverControllerAccessibility"];
  [a3 addObject:@"THScrollViewAccessibility"];
  [a3 addObject:@"THTOCViewAccessibility"];
  [a3 addObject:@"THTOCViewControllerAccessibility"];
  [a3 addObject:@"THToolbarAccessibility"];
  [a3 addObject:@"THToolbarControllerAccessibility"];
  [a3 addObject:@"THWAVAudioUIAccessibility"];
  [a3 addObject:@"THWDetailSliderAccessibility"];
  [a3 addObject:@"THWiOSExpandedViewAccessibility"];
  [a3 addObject:@"THWiOSExpandedViewControllerAccessibility"];
  [a3 addObject:@"THWIOSMovieRepAccessibility"];
  [a3 addObject:@"THWLabelControlRepAccessibility"];
  [a3 addObject:@"THWPHighlightControllerAccessibility"];
  [a3 addObject:@"THWPressableRepGestureTargetHandlerAccessibility"];
  [a3 addObject:@"TSWPassThroughViewAccessibility"];
  [a3 addObject:@"TSWPStorageAccessibility"];
  [a3 addObject:@"TSWPTextMagnifierRendererAccessibility"];
  [a3 addObject:@"TSWSelfContainedWPViewControllerAccessibility"];
  [a3 addObject:@"THWDrawablesWidgetRepAccessibility"];
}

@end