@interface HSAccessoryTuple
- (BOOL)isSetupComplete;
- (HMAccessory)accessory;
- (HSSetupStateMachine)stateMachine;
- (HSSetupStateMachineConfiguration)configuration;
- (NSString)accessoryCategoryOrPrimaryServiceType;
- (NSString)titleForAccessory;
- (NSString)userFriendlyAccessoryLocalizedCapitalizedDescription;
- (NSString)userFriendlyAccessoryLocalizedLowercaseDescription;
- (id)_moveToNextStep;
- (id)description;
- (id)titleForAccessoryWithDefaultValue:(id)a3;
- (int64_t)currentStep;
- (void)setAccessory:(id)a3;
- (void)setConfiguration:(id)a3;
- (void)setCurrentStep:(int64_t)a3;
- (void)setStateMachine:(id)a3;
- (void)setTitleForAccessory:(id)a3;
@end

@implementation HSAccessoryTuple

- (id)description
{
  v3 = (objc_class *)objc_opt_class();
  v4 = NSStringFromClass(v3);
  v5 = [(HSAccessoryTuple *)self userFriendlyAccessoryLocalizedCapitalizedDescription];
  v6 = +[HSSetupContentProvider stringForHSProxCardSetupUIStep:[(HSAccessoryTuple *)self currentStep]];
  v7 = [(HSAccessoryTuple *)self accessory];
  v8 = +[NSString stringWithFormat:@"%@ <accessoryCategoryOrPrimaryServiceType %@, currentStep %@, accessory %@>", v4, v5, v6, v7];

  return v8;
}

- (HMAccessory)accessory
{
  v2 = [(HSAccessoryTuple *)self configuration];
  v3 = [v2 addedAccessory];

  return (HMAccessory *)v3;
}

- (void)setAccessory:(id)a3
{
  id v4 = a3;
  id v5 = [(HSAccessoryTuple *)self configuration];
  [v5 setAddedAccessory:v4];
}

- (NSString)accessoryCategoryOrPrimaryServiceType
{
  v3 = [(HSAccessoryTuple *)self accessory];
  id v4 = [v3 hf_categoryOrPrimaryServiceType];
  id v5 = v4;
  if (v4)
  {
    v6 = v4;
  }
  else
  {
    v7 = [(HSAccessoryTuple *)self configuration];
    v8 = [v7 setupDescription];
    v9 = [v8 category];
    uint64_t v10 = [v9 categoryType];
    v11 = (void *)v10;
    v12 = HMAccessoryCategoryTypeOther;
    if (v10) {
      v12 = (NSString *)v10;
    }
    v6 = v12;
  }

  return v6;
}

- (NSString)userFriendlyAccessoryLocalizedCapitalizedDescription
{
  v3 = [(HSAccessoryTuple *)self accessory];
  id v4 = v3;
  if (v3)
  {
    id v5 = [v3 hf_userFriendlyLocalizedCapitalizedDescription];
  }
  else
  {
    v6 = [(HSAccessoryTuple *)self accessoryCategoryOrPrimaryServiceType];
    id v5 = +[HMAccessory hf_userFriendlyLocalizedCapitalizedDescription:v6];
  }

  return (NSString *)v5;
}

- (NSString)userFriendlyAccessoryLocalizedLowercaseDescription
{
  v3 = [(HSAccessoryTuple *)self accessory];
  id v4 = v3;
  if (v3)
  {
    id v5 = [v3 hf_userFriendlyLocalizedLowercaseDescription];
  }
  else
  {
    v6 = [(HSAccessoryTuple *)self accessoryCategoryOrPrimaryServiceType];
    id v5 = +[HMAccessory hf_userFriendlyLocalizedLowercaseDescription:v6];
  }

  return (NSString *)v5;
}

- (NSString)titleForAccessory
{
  v3 = [(HSAccessoryTuple *)self userFriendlyAccessoryLocalizedCapitalizedDescription];
  id v4 = [(HSAccessoryTuple *)self titleForAccessoryWithDefaultValue:v3];

  return (NSString *)v4;
}

- (id)titleForAccessoryWithDefaultValue:(id)a3
{
  id v4 = a3;
  id v5 = [(HSAccessoryTuple *)self configuration];
  v6 = [v5 userGivenAccessoryName];

  if (v6)
  {
    v7 = [(HSAccessoryTuple *)self configuration];
    id v8 = [v7 userGivenAccessoryName];
    goto LABEL_22;
  }
  v9 = [(HSAccessoryTuple *)self accessory];
  v7 = [v9 hf_primaryService];

  uint64_t v10 = [(HSAccessoryTuple *)self accessory];
  v11 = [v10 configuredName];

  v12 = [v7 serviceType];
  unsigned int v13 = [v12 isEqualToString:HMServiceTypeTelevision];

  if (!v13)
  {
    v14 = v11;
    if (!v11) {
      goto LABEL_7;
    }
    goto LABEL_10;
  }
  v14 = [v7 configuredName];

  v15 = [(HSAccessoryTuple *)self configuration];
  uint64_t v16 = [v15 home];
  v17 = [(id)v16 roomForEntireHome];
  id v18 = [v17 name];

  LOBYTE(v16) = [v14 isEqualToString:v18];
  v19 = [(HSAccessoryTuple *)self configuration];
  v20 = [v19 roomName];
  unsigned int v21 = [v14 isEqualToString:v20];

  if ((v16 & 1) == 0 && !v21)
  {

    if (!v14)
    {
LABEL_7:
      v22 = [(HSAccessoryTuple *)self configuration];
      v23 = [v22 setupDescription];
      v24 = [v23 hf_marketingName];
      v25 = v24;
      if (v24)
      {
        id v18 = v24;
      }
      else
      {
        v33 = [(HSAccessoryTuple *)self configuration];
        v26 = [v33 setupDescription];
        v27 = [v26 accessoryName];
        v28 = v27;
        if (v27)
        {
          id v18 = v27;
        }
        else
        {
          v29 = [(HSAccessoryTuple *)self accessory];
          id v18 = [v29 name];
        }
      }

      goto LABEL_17;
    }
LABEL_10:
    id v18 = v14;
LABEL_17:
    v30 = +[HFUtilities sanitizeAutoGeneratedHomeKitName:v18];
    if ([v30 length]) {
      v31 = v30;
    }
    else {
      v31 = v4;
    }
    id v8 = v31;

    goto LABEL_21;
  }
  id v8 = v4;
LABEL_21:

LABEL_22:

  return v8;
}

- (id)_moveToNextStep
{
  if ([(HSAccessoryTuple *)self isSetupComplete])
  {
    v3 = +[NAFuture futureWithResult:&__kCFBooleanTrue];
  }
  else
  {
    id v4 = [(HSAccessoryTuple *)self stateMachine];
    int64_t v5 = [(HSAccessoryTuple *)self currentStep];
    v6 = [(HSAccessoryTuple *)self configuration];
    -[HSAccessoryTuple setCurrentStep:](self, "setCurrentStep:", [v4 stepFollowingStep:v5 withConfiguration:v6]);

    v7 = +[HSSetupContentProvider stringForHSProxCardSetupUIStep:[(HSAccessoryTuple *)self currentStep]];
    id v8 = HFLogForCategory();
    if (os_log_type_enabled(v8, OS_LOG_TYPE_DEFAULT))
    {
      *(_DWORD *)buf = 138412290;
      v19 = v7;
      _os_log_impl((void *)&_mh_execute_header, v8, OS_LOG_TYPE_DEFAULT, "Calculating potential skip of: %@", buf, 0xCu);
    }

    v9 = [(HSAccessoryTuple *)self stateMachine];
    int64_t v10 = [(HSAccessoryTuple *)self currentStep];
    v11 = [(HSAccessoryTuple *)self configuration];
    v12 = [v9 shouldSkipStep:v10 withConfiguration:v11];
    v15[0] = _NSConcreteStackBlock;
    v15[1] = 3221225472;
    v15[2] = sub_100060858;
    v15[3] = &unk_1000AA7F8;
    id v16 = v7;
    v17 = self;
    id v13 = v7;
    v3 = [v12 flatMap:v15];
  }

  return v3;
}

- (BOOL)isSetupComplete
{
  return (id)[(HSAccessoryTuple *)self currentStep] == (id)52;
}

- (void)setTitleForAccessory:(id)a3
{
}

- (HSSetupStateMachine)stateMachine
{
  return (HSSetupStateMachine *)objc_getProperty(self, a2, 16, 1);
}

- (void)setStateMachine:(id)a3
{
}

- (HSSetupStateMachineConfiguration)configuration
{
  return (HSSetupStateMachineConfiguration *)objc_getProperty(self, a2, 24, 1);
}

- (void)setConfiguration:(id)a3
{
}

- (int64_t)currentStep
{
  return self->_currentStep;
}

- (void)setCurrentStep:(int64_t)a3
{
  self->_currentStep = a3;
}

- (void).cxx_destruct
{
  objc_storeStrong((id *)&self->_configuration, 0);
  objc_storeStrong((id *)&self->_stateMachine, 0);

  objc_storeStrong((id *)&self->_titleForAccessory, 0);
}

@end